name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  setup-server:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      PORT: 3000
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 20
    - name: Install dependencies
      run: npm ci

    - name: Install Next and start server
      run: |
          npm install next@latest react@latest react-dom@latest
          npm run dev &
          echo "Waiting for server to start..."
          npx wait-on http://localhost:$PORT
          echo "Server started successfully."   

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npx playwright test
    
    - name: Stop server
      run: pkill -f "npm run dev" || true    
