name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  setup-server:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      PORT: 3000
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci

    - name: Install Next and start server
      run: |
          npm install next@latest react@latest react-dom@latest
          npm run dev &
          echo "Waiting for server to start..."
          npx wait-on http://localhost:$PORT
          echo "Server started successfully."   
  
  playwright_tests:
    runs-on: ubuntu-latest        
    needs: setup-server
        
    steps:
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npx playwright test

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
    
    - name: Stop server
      run: pkill -f "npm run dev" || true    
